/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.testproject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        logger.debug("getGreeting() method called");
        return "Hello World!";
    }

    public static void main(String[] args) {
        logger.info("Application starting...");
        
        App app = new App();
        String greeting = app.getGreeting();
        System.out.println(greeting);
        
        logger.info("Application finished successfully");
        logger.debug("Greeting was: {}", greeting);
    }
}
